# generated by datamodel-codegen:
#   filename:  stratum
#   timestamp: 2026-09-16T18:22:06+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    hashrate_15m: int
    hashrate_1h: int
    hashrate_24h: int
    total_hashes: int
    total_stratum_shares: int
    last_share_found_time: int
    shares_found: int
    shares_failed: int
    average_effort: float
    current_effort: float
    connections: int
    incoming_connections: int
    block_reward_share_percent: float
    wallet: str
    workers: list[str]
