# generated by datamodel-codegen:
#   filename:  p2p
#   timestamp: 2026-09-16T18:21:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    connections: int
    incoming_connections: int
    peer_list_size: int
    peers: list[str]
    uptime: int
    zmq_last_active: int
