# generated by datamodel-codegen:
#   filename:  merge_mining
#   timestamp: 2026-09-16T18:20:59+00:00

from __future__ import annotations

from pydantic import BaseModel


class Chain(BaseModel):
    api: str
    id: str
    host: str
    channel_state: str
    wallet: str
    height: int
    difficulty: int
    reward: int
    fees: int
    timestamp: int


class Model(BaseModel):
    chains: list[Chain]
