# generated by datamodel-codegen:
#   filename:  console
#   timestamp: 2026-09-16T18:21:48+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    mode: str
    tcp_port: int
    cookie: str
