# generated by datamodel-codegen:
#   filename:  stats
#   timestamp: 2026-09-16T18:22:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    difficulty: int
    hash: str
    height: int
    reward: int
    timestamp: int
