# generated by datamodel-codegen:
#   filename:  stats
#   timestamp: 2026-09-16T18:22:52+00:00

from __future__ import annotations

from pydantic import BaseModel


class PoolStatistics(BaseModel):
    hashRate: int
    miners: int
    totalHashes: int
    lastBlockFoundTime: int
    lastBlockFound: int
    totalBlocksFound: int
    pplnsWeight: int
    pplnsWindowSize: int
    sidechainDifficulty: int
    sidechainHeight: int


class Model(BaseModel):
    pool_list: list[str]
    pool_statistics: PoolStatistics
