# generated by datamodel-codegen:
#   filename:  stats_mod
#   timestamp: 2026-09-16T18:23:35+00:00

from __future__ import annotations

from pydantic import BaseModel


class Port(BaseModel):
    port: int
    tls: bool


class Config(BaseModel):
    ports: list[Port]
    fee: int
    minPaymentThreshold: int


class Network(BaseModel):
    height: int


class Stats(BaseModel):
    lastBlockFound: str


class Pool(BaseModel):
    stats: Stats
    blocks: list[str]
    miners: int
    hashrate: int
    roundHashes: int


class Model(BaseModel):
    config: Config
    network: Network
    pool: Pool
